image: node:latest

stages:
  - test
  - build
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

dummy-test:
  stage: test
  script:
    - echo "dummy-test went well"
  only:
    - develop

pull-develop-on-ec2:
  stage: build
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-103-26.ap-south-1.compute.amazonaws.com "cd demo-express && git checkout develop && git pull"
    - echo "pulling develop went well"
  only:
    - develop

build-node-modules:
  stage: build
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-103-26.ap-south-1.compute.amazonaws.com "cd demo-express && npm i"
    - echo "npm i went well"
  only:
    - develop

pm2-restart:
  type: command
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-103-26.ap-south-1.compute.amazonaws.com "cd demo-express && pm2 restart pm2.config.js"
    - echo "pm2-restart went well"
  only:
    - develop
