module.exports = {
  info: {
    productId: "12345",
    code: "VOLLEY_INDOOR_SHOES_CUSHION",
    title: "COURT TEAM BOUNCE INDOOR SHOES",
    header: "CUSHIONED SHOES FOR OWNING INDOOR COURTS.",
    category: "shoes",
    tags: ["volleyball", "badminton", "handball"],
    regions: ["eu"],
    description: `All the support you need to up your indoor game.These Court Team Bounce shoes
        keep you comfortable in fast-moving sports like volleyball, handball and badminton. Their lightweight
        mesh upper adds mobility without sacrificing stability. The full-length Bounce midsole cushions every landing.`,
    recyleInfo:
      "This product is made with Primegreen, a series of high-performance recycled materials",
  },
  items: [
    {
      color: "core-black",
      stock: 15,
      size: 3.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_0",
    },
    {
      color: "core-black",
      stock: 15,
      size: 8,
      price: 120,
      currency: "eur",
      productId: "12345",
      itemId: "12345_2",
    },
    {
      color: "core-black",
      stock: 15,
      size: 10.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_3",
    },
    {
      color: "core-black",
      stock: 0,
      size: 4.5,
      price: 80,
      currency: "eur",
      productId: "12345",
      itemId: "12345_4",
    },
    {
      color: "core-black",
      stock: 15,
      size: 5,
      price: 80,
      currency: "eur",
      productId: "12345",
      itemId: "12345_7",
    },
    {
      color: "core-black",
      stock: 15,
      size: 8.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_8",
    },
    {
      color: "core-black",
      stock: 15,
      size: 11,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_9",
    },
    {
      color: "core-black",
      stock: 15,
      size: 5.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_10",
    },
    {
      color: "core-black",
      stock: 15,
      size: 6,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_13",
    },
    {
      color: "core-black",
      stock: 15,
      size: 9,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_14",
    },
    {
      color: "core-black",
      stock: 15,
      size: 11.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_15",
    },
    {
      color: "core-black",
      stock: 15,
      size: 6.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_16",
    },
    {
      color: "core-black",
      stock: 15,
      size: 13,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_17",
    },
    {
      color: "core-black",
      stock: 0,
      size: 7,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_19",
    },
    {
      color: "core-black",
      stock: 0,
      size: 9.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_20",
    },
    {
      color: "core-black",
      stock: 0,
      size: 12,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_21",
    },
    {
      color: "core-black",
      stock: 0,
      size: 7.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_22",
    },
    {
      color: "core-black",
      stock: 1,
      size: 10,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_25",
    },
    {
      color: "core-black",
      stock: 1,
      size: 12.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_26",
    },
    {
      color: "cloud-white",
      stock: 0,
      size: 3.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_28",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 8,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_30",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 10.5,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_31",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 4.5,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_32",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_35",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 8.5,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_36",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 11,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_37",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 5.5,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_38",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 6,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_41",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 9,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_42",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 11.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_43",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 6.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_44",
    },
    {
      color: "cloud-white",
      stock: 15,
      size: 13,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_45",
    },
    {
      color: "cloud-white",
      stock: 0,
      size: 7,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_47",
    },
    {
      color: "cloud-white",
      stock: 0,
      size: 9.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_48",
    },
    {
      color: "cloud-white",
      stock: 0,
      size: 12,
      price: 70,
      currency: "eur",
      productId: "12345",
      itemId: "12345_49",
    },
    {
      color: "cloud-white",
      stock: 0,
      size: 7.5,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_50",
    },
    {
      color: "cloud-white",
      stock: 1,
      size: 10,
      price: 140,
      currency: "eur",
      productId: "12345",
      itemId: "12345_53",
    },
    {
      color: "cloud-white",
      stock: 1,
      size: 12.5,
      price: 210,
      currency: "eur",
      productId: "12345",
      itemId: "12345_54",
    },
    {
      color: "grey-four",
      stock: 1,
      size: 13,
      price: 78,
      currency: "eur",
      productId: "12345",
      itemId: "12345_54",
    }
  ],
  ratings: {
    productId: "12345",
    ratings: [
      {
        stars: 3,
        userEmail: "kk@kk.com",
        comment: "just avarage",
      },
      {
        stars: 4,
        userEmail: "kk1@kk.com",
        comment: "good",
      },
      {
        stars: 5,
        userEmail: "kk2@kk.com",
        comment: "awesome",
      },
      {
        stars: 5,
        userEmail: "kk3@kk.com",
        comment: "awesome2",
      },
      {
        stars: 5,
        userEmail: "kk4@kk.com",
        comment: "awesome3",
      },
      {
        stars: 5,
        userEmail: "kk5@kk.com",
        comment: "awesome4",
      },
      {
        stars: 4,
        userEmail: "kk6@kk.com",
        comment: "awesome5",
      },
      {
        stars: 4,
        userEmail: "kk7@kk.com",
        comment: "awesome7",
      },
    ],
  },
};
